// This file was generated by Slice Machine. You may edit this file.

import * as React from "react";
import { graphql } from "gatsby";

import { CallToActionProps } from "./types";

export { CallToActionProps };

// TODO: Implement the CallToAction component.
//
// → Learn how to render this component with <SliceZone>
//   https://prismic.io/docs/technologies/template-slices-gatsby
export const CallToAction = ({ slice }: CallToActionProps): JSX.Element => {
	return (
		<section>Placeholder CallToAction component - {slice.variation}</section>
	);
};

// TODO: Create a GraphQL fragment for each Slice variation.
//
// → Learn how to query for fields
//   https://prismic.io/docs/technologies/retrieve-fields-and-slices-gatsby
//
// → Learn how to use this GraphQL fragment
//   https://prismic.io/docs/technologies/fragments-gatsby
export const fragments = graphql`
	fragment PrismicCallToActionDefault on PrismicCallToActionDefault {
		slice_type
		variation
		primary {
			title {
				text
			}
			description {
				text
			}
		}
	}
	fragment PrismicCallToActionWithButton on PrismicCallToActionWithButton {
		slice_type
		variation
		primary {
			title {
				text
			}
			description {
				text
			}
			buttonText {
				text
			}
			buttonLink {
				url
				target
			}
		}
	}
`;
