// This file was generated by Slice Machine. DO NOT EDIT.

import { SliceComponentProps } from "@prismicio/react";

import {
	PrismicCallToActionDefaultFragment,
	PrismicCallToActionWithButtonFragment,
} from "../../types.generated";

export type CallToActionSlice = { slice_type: "call_to_action" } & (
	| ({ variation: "default" } & PrismicCallToActionDefaultFragment)
	| ({ variation: "withButton" } & PrismicCallToActionWithButtonFragment)
);

export type CallToActionProps = SliceComponentProps<CallToActionSlice>;
