// This file was generated by Slice Machine. You may edit this file.

import * as React from "react";
import { graphql, PageProps } from "gatsby";
import { SliceZone } from "@prismicio/react";

import { PrismicPageTemplateQuery } from "../types.generated";
import {
	prismicPageDataBodyComponents,
	PrismicPageDataBodySlice,
} from "../slices";

type PrismicPageTemplateProps = PageProps<
	PrismicPageTemplateQuery,
	{ id: string }
>;

const PrismicPageTemplate = (props: PrismicPageTemplateProps): JSX.Element => {
	const prismicPage = props.data.prismicPage;
	if (!prismicPage) {
		throw new Error(
			`Could not find a PrismicPage with ID: ${props.pageContext.id}`,
		);
	}

	const prismicPageDataBodySlices = prismicPage.data
		.body as PrismicPageDataBodySlice[];

	return (
		<SliceZone
			slices={prismicPageDataBodySlices}
			components={prismicPageDataBodyComponents}
		/>
	);
};

export default PrismicPageTemplate;

export const query = graphql`
	query PrismicPageTemplate($id: String!) {
		prismicPage(id: { eq: $id }) {
			_previewable
			data {
				body {
					...PrismicPageDataBody
				}
			}
		}
	}
`;
