// This file was generated by Slice Machine. You may edit this file.

import * as React from "react";
import { graphql, PageProps } from "gatsby";
import { SliceZone } from "@prismicio/react";

import { PrismicPageTemplateQuery } from "../types.generated";
import {
	prismicPageDataBodyComponents,
	PrismicPageDataBodySlice,
} from "../slices";

type PrismicPageTemplateProps = PageProps<PrismicPageTemplateQuery>;

const PrismicPageTemplate = (props: PrismicPageTemplateProps): JSX.Element => {
	// eslint-disable-next-line @typescript-eslint/no-non-null-assertion
	const page = props.data.prismicPage!;
	const pageDataBodySlices = page.data.body as PrismicPageDataBodySlice[];

	return (
		<SliceZone
			slices={pageDataBodySlices}
			components={prismicPageDataBodyComponents}
		/>
	);
};

export default PrismicPageTemplate;

export const query = graphql`
	query PrismicPageTemplate($id: String!) {
		prismicPage(id: { eq: $id }) {
			_previewable
			data {
				body {
					...PrismicPageDataBody
				}
			}
		}
	}
`;
