// This file was generated by Slice Machine. You may edit this file.

import * as React from "react";
import { graphql } from "gatsby";

import { HeroProps } from "./types";

export { HeroProps };

// TODO: Implement the Hero component.
//
// → Learn how to render this component with <SliceZone>
//   https://prismic.io/docs/technologies/template-slices-gatsby
export const Hero = ({ slice }: HeroProps): JSX.Element => {
	return <section>Placeholder Hero component - {slice.variation}</section>;
};

// TODO: Create a GraphQL fragment for each Slice variation.
//
// → Learn how to query for fields
//   https://prismic.io/docs/technologies/retrieve-fields-and-slices-gatsby
//
// → Learn how to use this GraphQL fragment
//   https://prismic.io/docs/technologies/fragments-gatsby
export const fragments = graphql`
	fragment PrismicHeroDefault on PrismicHeroDefault {
		slice_type
		primary {
			title {
				text
			}
			description {
				text
			}
		}
	}
	fragment PrismicHeroWithBackground on PrismicHeroWithBackground {
		slice_type
		primary {
			title {
				text
			}
			description {
				text
			}
			backgroundImage {
				url
			}
		}
	}
`;
