// This file was generated by Slice Machine. You may edit this file.

import * as React from "react";
import { graphql } from "gatsby";

import { HeroSliceComponentProps } from "./types";

export type HeroProps = {
	variation: HeroSliceComponentProps["slice"]["variation"];
	title?: string;
	description?: string;
	backroundUrl?: string;
};

// TODO: Implement the Hero component.
//
// → Learn how to render this component with <SliceZone>
//   https://prismic.io/docs/technologies/template-slices-gatsby
export const Hero = ({
	title,
	description,
	backroundUrl,
}: HeroProps): JSX.Element => {
	return (
		<section
			style={{
				backgroundImage: backroundUrl ? `url('${backroundUrl}')` : undefined,
			}}
		>
			{title && <h1>{title}</h1>}
			{description && <p>{description}</p>}
		</section>
	);
};

export const mapSliceToProps = ({
	slice,
}: HeroSliceComponentProps): HeroProps => {
	switch (slice.variation) {
		case "default": {
			return {
				variation: slice.variation,
				title: slice.primary.title?.text,
				description: slice.primary.description?.text,
			};
		}

		case "withBackground": {
			return {
				variation: slice.variation,
				title: slice.primary.title?.text,
				description: slice.primary.description?.text,
				backroundUrl: slice.primary.backgroundImage?.url,
			};
		}
	}
};

// TODO: Create a GraphQL fragment for each Slice variation.
//
// → Learn how to query for fields
//   https://prismic.io/docs/technologies/retrieve-fields-and-slices-gatsby
//
// → Learn how to use this GraphQL fragment
//   https://prismic.io/docs/technologies/fragments-gatsby
export const fragments = graphql`
	fragment PrismicHeroDefault on PrismicHeroDefault {
		slice_type
		variation
		primary {
			title {
				text
			}
			description {
				text
			}
		}
	}
	fragment PrismicHeroWithBackground on PrismicHeroWithBackground {
		slice_type
		variation
		primary {
			title {
				text
			}
			description {
				text
			}
			backgroundImage {
				url
			}
		}
	}
`;
