// Code generated by Slice Machine. DO NOT EDIT.

import { HeroSlice } from "./types";

export const defaultVariation: HeroSlice & {
	variation: "default";
} = {
	slice_type: "hero",
	variation: "default",
	primary: {
		title: {
			text: "Lorem ipsum",
		},
		description: {
			text: "Donec ullamcorper nulla non metus auctor fringilla.",
		},
	},
};

export const withBackgroundVariation: HeroSlice & {
	variation: "withBackground";
} = {
	slice_type: "hero",
	variation: "withBackground",
	primary: {
		title: {
			text: "Lorem ipsum",
		},
		description: {
			text: "Donec ullamcorper nulla non metus auctor fringilla.",
		},
		backgroundImage: {
			url: "https://images.unsplash.com/photo-1550684848-86a5d8727436?auto=format&fit=crop&w=2550&q=80",
		},
	},
};
