// Code generated by Slice Machine. DO NOT EDIT.

import { SliceComponentProps } from "@prismicio/react";

import {
	PrismicHeroDefaultFragment,
	PrismicHeroWithBackgroundFragment,
} from "../../types.generated";

export type HeroSlice = { slice_type: "hero" } & (
	| ({ variation: "default" } & PrismicHeroDefaultFragment)
	| ({ variation: "withBackground" } & PrismicHeroWithBackgroundFragment)
);

export type HeroSliceComponentProps = SliceComponentProps<HeroSlice>;
