// Code generated by Slice Machine. DO NOT EDIT.

import loadable from "@loadable/component";
import { graphql } from "gatsby";

import { HeroSlice } from "./Hero/types";
import { CallToActionSlice } from "./CallToAction/types";

export type PrismicPageDataBodySlice = HeroSlice | CallToActionSlice;

export const prismicPageDataBodyComponents = {
	hero: loadable(async () => (await import("./Hero")).Hero),
	call_to_action: loadable(
		async () => (await import("./CallToAction")).CallToAction,
	),
};

export const fragments = graphql`
	fragment PrismicPageDataBody on PrismicPageDataBodySlicesType {
		... on PrismicSliceType {
			slice_type
		}
		... on PrismicSharedSliceType {
			variation
		}
		...PrismicCallToAction
		...PrismicHero
	}
`;
