// Code generated by Slice Machine. DO NOT EDIT.

import * as React from "react";
import { graphql } from "gatsby";
import { SliceZoneComponents } from "@prismicio/react";
import loadable from "@loadable/component";

import { HeroSlice } from "./Hero/types";
import { CallToActionSlice } from "./CallToAction/types";

export type PrismicPageDataBodySlice = HeroSlice | CallToActionSlice;

export const prismicPageDataBodyComponents: SliceZoneComponents<PrismicPageDataBodySlice> =
	{
		hero: loadable(async () => {
			const module = await import("./Hero");
			const Comp = module.Hero;

			return (props) => <Comp {...module.mapSliceToProps(props)} />;
		}),
		call_to_action: loadable(
			async () => (await import("./CallToAction")).CallToAction,
		),
	};

export const fragments = graphql`
	fragment PrismicPageDataBody on PrismicPageDataBodySlicesType {
		... on PrismicSliceType {
			slice_type
		}
		... on PrismicSharedSliceType {
			variation
		}
		...PrismicCallToAction
		...PrismicHero
	}
`;
