// Code generated by Slice Machine. DO NOT EDIT.

import loadable from "@loadable/component";

export const pageDataBodyComponents = {
	hero: loadable(() => (await import("./Hero")).Hero),
	call_to_action: loadable(() => (await import("./CallToAction")).CallToAction),
};
